### PR TITLE
Adding ZEOS Token, ZEOS - zk-SNARKs Privacy on the EOS Blockchain. 

### PR DESCRIPTION
**Pull request by bngone**
## How to add token?

- [x] Add metadata to [`tokens.json`](tokens.json)

```json
{
    "name": "<NAME>",
    "logo": "https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/<SYMBOL>.png",
    "logo_lg": "https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/<SYMBOL>.png",
    "symbol": "<SYMBOL>",
    "account": "<CONTRACT NAME>",
    "chain": "eos"
}
```

- [x] Add token logo `*.png` to [`./logos`](./logos) folder

### CODE REVIEW

**Comment by bngone** [comment]
Please add ZEOS and it meta data to list Thank you.

**Comment by jafri** [comment]
Adds 2 tokens to json for some reason, only add one

**Comment by bngone** [comment]
> Adds 2 tokens to JSON for some reason, only add one

ok sir I'm searching for the other one to remove it

**Comment by bngone** [comment]
I'm ZEOS Contributor, That's why I'm Adding ZEOS Because up to now ZEOS Logo is not showing on Blockexplorer. And the other one BNG is my Independent Project on EOS Blockchain.

Thank You Sir.

**Comment by bngone** [comment]
> Adds 2 tokens to JSON for some reason, only add one

Yes, Sir, The other one was removed, Thank You.

**Comment by bngone** [comment]
Thank You, Sir.

**Pull request merged**
