### PR TITLE
add dogzilla WOOF token

### PR DESCRIPTION
**Pull request by buzzking00**
## How to add token?

- [ ] Add metadata to [`tokens.json`](tokens.json)

```json
{
    "name": "<NAME>",
    "logo": "https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/<SYMBOL>.png",
    "logo_lg": "https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/<SYMBOL>.png",
    "symbol": "<SYMBOL>",
    "account": "<CONTRACT NAME>",
    "chain": "<chain>"
}
```

- [ ] Add token logo `*.png` or `*.jpg` to [`./logos`](./logos) folder

- [ ] Supported chains:
  - eos
  - telos
  - wax
  - proton

- [ ] Token `name` must be sorted alphabetically in `tokens.json`
- [ ] logo URL must start with `https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/logos/<SYMBOL>.png`

### CODE REVIEW

**Comment by DenisCarriere** [comment]
Please follow the "How to add token" instructions

Only *.png or *.jpg is accepted

**Comment by buzzking00** [comment]
Oooooh is there any reason avif files are not accepted?

**Comment by buzzking00** [comment]
The Logo image has been changed to PNG. Thank you!

**Comment by buzzking00** [comment]
Hello, wanted to check if you see the image file change:
https://github.com/eoscafe/eos-airdrops/commit/be20260d9145cef7d598071d51a38586ccd597fd

**Pull request closed without merging**
